"""agregar es_principal a product_image

Revision ID: 159f56169e7a
Revises: 97a7d56c4cc8
Create Date: 2026-07-02 20:17:02.845509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159f56169e7a'
down_revision = '97a7d56c4cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_principal', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.drop_column('es_principal')

    # ### end Alembic commands ###
