"""Agregar productos destacados

Revision ID: 5fcb99934bc3
Revises: 67de8065027f
Create Date: 2026-01-18 23:22:10.369571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fcb99934bc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mostrar_en_index', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('etiqueta', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('etiqueta')
        batch_op.drop_column('mostrar_en_index')

    # ### end Alembic commands ###
