"""Actualizar modelo CuentaPago

Revision ID: 67de8065027f
Revises: b089eff2cd2e
Create Date: 2025-11-11 16:57:36.112469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67de8065027f'
down_revision = 'b089eff2cd2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuenta_pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banco', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('alias', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cbu', sa.String(length=22), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuenta_pago', schema=None) as batch_op:
        batch_op.drop_column('cbu')
        batch_op.drop_column('alias')
        batch_op.drop_column('banco')

    # ### end Alembic commands ###
