"""restaurar columnas alias y cbu en cuenta_pago

Revision ID: 97a7d56c4cc8
Revises: 794569c53f93
Create Date: 2026-06-17 18:34:03.087280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97a7d56c4cc8'
down_revision = '794569c53f93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuenta_pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alias', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cbu', sa.String(length=22), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuenta_pago', schema=None) as batch_op:
        batch_op.drop_column('cbu')
        batch_op.drop_column('alias')

    # ### end Alembic commands ###
