"""Migración limpia con CuentaPago

Revision ID: b089eff2cd2e
Revises: 
Create Date: 2025-11-01 11:04:35.786246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b089eff2cd2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_cuenta_pago')
    with op.batch_alter_table('cuenta_pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('public_key', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('access_token', sa.String(length=200), nullable=True))
        batch_op.drop_column('alias')
        batch_op.drop_column('cbu')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuenta_pago_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('estado_pago', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_order_cuenta_pago', 'cuenta_pago', ['cuenta_pago_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('estado_pago')
        batch_op.drop_column('cuenta_pago_id')

    with op.batch_alter_table('cuenta_pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cbu', sa.VARCHAR(length=22), nullable=False))
        batch_op.add_column(sa.Column('alias', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('access_token')
        batch_op.drop_column('public_key')
        batch_op.drop_column('email')

    op.create_table('_alembic_tmp_cuenta_pago',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('activo', sa.BOOLEAN(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('public_key', sa.VARCHAR(length=200), nullable=True),
    sa.Column('access_token', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
