"""Elimino columna imagen de Product y creo ProductImage

Revision ID: f58e9ef745bc
Revises: 
Create Date: 2025-09-18 18:15:24.344681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58e9ef745bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('imagen')
        batch_op.drop_column('clasificacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clasificacion', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('imagen', sa.VARCHAR(length=200), nullable=False))

    # ### end Alembic commands ###
